### ISSUE TITLE
[staticMarkdown:ec9d0885.37db48] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /data/node_modules/@gerhobbelt/markdown-it-footnote/dist/markdownItFootnote.js

### ISSUE THREAD

**Issue by janvda** [TotallyInformation/node-red-contrib-static-markdown#12]
Here the output of my log file

```
19 Feb 10:46:39 - [info] 

Welcome to Node-RED
===================

19 Feb 10:46:39 - [info] Node-RED version: v1.2.9
19 Feb 10:46:39 - [info] Node.js  version: v12.20.1
19 Feb 10:46:39 - [info] Linux 4.19.121-linuxkit x64 LE
19 Feb 10:46:39 - [info] Loading palette nodes
19 Feb 10:46:40 - [info] mDashboard version 2.19.4-beta started at /mui
19 Feb 10:46:40 - [info] Dashboard version 2.23.4 started at /ui
19 Feb 10:46:40 - [info] Settings file  : /data/settings.js
19 Feb 10:46:40 - [info] Context store  : 'default' [module=memory]
19 Feb 10:46:40 - [info] User directory : /data
19 Feb 10:46:40 - [warn] Projects disabled : editorTheme.projects.enabled=false
19 Feb 10:46:40 - [info] Flows file     : /data/flows.json
19 Feb 10:46:40 - [info] Server now running at http://127.0.0.1:1880/
19 Feb 10:46:40 - [info] Starting flows
19 Feb 10:46:41 - [error] [staticMarkdown:ec9d0885.37db48] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /data/node_modules/@gerhobbelt/markdown-it-footnote/dist/markdownItFootnote.js
require() of ES modules is not supported.
require() of /data/node_modules/@gerhobbelt/markdown-it-footnote/dist/markdownItFootnote.js from /data/node_modules/node-red-contrib-static-markdown/nodes/lib/serveMarkdown.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename markdownItFootnote.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /data/node_modules/@gerhobbelt/markdown-it-footnote/package.json.

19 Feb 10:46:41 - [info] Started flows
19 Feb 10:46:41 - [info] [sqlitedb:c54d228d.362e2] opened /data/worldgame.db ok
[INFO]  @slack/client:RTMClient:3 unable to RTM start: An API error occurred: invalid_auth
19 Feb 10:46:41 - [info] [slack-config:$slack_token] disconnected from slack with token: ${slack_...en}
failed starting slack session Error: An API error occurred: invalid_auth
    at platformErrorFromResult (/data/node_modules/@slack/client/dist/WebClient.js:770:42)
    at /data/node_modules/@slack/client/dist/WebClient.js:484:39
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'slackclient_platform_error',
  data: { ok: false, error: 'invalid_auth' }
}
```

**Comment by janvda** [comment]
**Root cause:**

A new version (v3.0.2-5) of [@gerhobbelt/markdown-it-footnote](https://www.npmjs.com/package/@gerhobbelt/markdown-it-footnote) is created at the beginning of February 2021 which introduced this problem.

Note that `package.json` contained following lines:

```
  "dependencies": {
    "@gerhobbelt/markdown-it-footnote": "^3.0.2-4",
    "@gerhobbelt/markdown-it-include": "^1.1.3-7",
```

So rebuilding it after February 2021 meant that no longer v3.0.2-4 is used but new version v3.0.2-5 is used.

**Fix**

Change  `package.json` in order to force it to use the correct version of `@gerhobbelt/markdown-it-footnote`
```
  "dependencies": {
    "@gerhobbelt/markdown-it-footnote": "3.0.2-4",
    "@gerhobbelt/markdown-it-include": "^1.1.3-7",
```
