### ISSUE TITLE
test.md is reporting TypeError: Cannot read property ‘attrJoin’ of undefined

### ISSUE THREAD

**Issue by janvda** [TotallyInformation/node-red-contrib-static-markdown#7]
I have first reported the issue in node-red forum:
* https://discourse.nodered.org/t/node-red-contrib-static-markdown-is-reporting-typeerror-cannot-read-property-attrjoin-of-undefined/32081

Here below I have copy pasted description from this node-red forum topic

---
In order to get this issue I have cloned this github repository.
so that I can test that the markdown in the example folder `docs/test-md-library` is properly rendered.

This seems to be the case for the [index.md](https://github.com/TotallyInformation/node-red-contrib-static-markdown/blob/master/docs/test-md-library/index.md) but not for the [test.md](https://github.com/TotallyInformation/node-red-contrib-static-markdown/blob/master/docs/test-md-library/test.md) in same folder.

So this is what I get when navigating to test.md:

![image|690x203](upload://5JuCeXV4FRrXoIpuaSQ9vyfCMLv.png) 

same error copy pasted as text:
```
TypeError: Cannot read property 'attrJoin' of undefined
    at Object.exports.addAttrs (/data/node_modules/@gerhobbelt/markdown-it-attrs/utils.js:105:13)
    at Object.transform (/data/node_modules/@gerhobbelt/markdown-it-attrs/patterns.js:131:15)
    at Array.curlyAttrs (/data/node_modules/@gerhobbelt/markdown-it-attrs/index.js:30:19)
    at Core.process (/data/node_modules/markdown-it/lib/parser_core.js:51:13)
    at MarkdownIt.parse (/data/node_modules/markdown-it/lib/index.js:523:13)
    at MarkdownIt.render (/data/node_modules/markdown-it/lib/index.js:543:36)
    at /data/node_modules/node-red-contrib-static-markdown/nodes/lib/serveMarkdown.js:213:39
    at /data/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

Note that it seems to be working fine for [index.md](https://github.com/TotallyInformation/node-red-contrib-static-markdown/blob/master/docs/test-md-library/index.md).  So when navigating to http://127.0.0.1:1880/md or http://127.0.0.1:1880/md/index.md : I am seeing the following page:
![image|438x499](upload://c8dOXEm46CBl7k6Shy8d6P1Lf6K.png)
![image](https://user-images.githubusercontent.com/17238398/91655041-35709080-eaae-11ea-8b79-6d43dfbf6b7d.png)

**Comment by janvda** [comment]
I think it is a markdown library compatibiity issue that is described in 
* https://github.com/arve0/markdown-it-attrs/issues/90

as I am getting the same error for my file `test2.md` with following content:

```
This is a paragraph of text with a *highlighted*{.hi} word in it.
```

It gives error
```
TypeError: Cannot read property 'attrJoin' of undefined
    at Object.exports.addAttrs (/data/node_modules/@gerhobbelt/markdown-it-attrs/utils.js:105:13)
    at Object.transform (/data/node_modules/@gerhobbelt/markdown-it-attrs/patterns.js:131:15)
    at Array.curlyAttrs (/data/node_modules/@gerhobbelt/markdown-it-attrs/index.js:30:19)
    at Core.process (/data/node_modules/markdown-it/lib/parser_core.js:51:13)
    at MarkdownIt.parse (/data/node_modules/markdown-it/lib/index.js:523:13)
    at MarkdownIt.render (/data/node_modules/markdown-it/lib/index.js:543:36)
    at /data/node_modules/node-red-contrib-static-markdown/nodes/lib/serveMarkdown.js:213:39
    at /data/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```
